name: Release

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -r requirements.dev.in
      - name: Build package
        run: |-
          python3 -m build
      - name: Create Github Release
        run: |-
          export VERSION=`grep __version__ passwords/__init__.py | grep -o '[0-9][^"]*'`
          gh release create $VERSION --title $VERSION --generate-notes
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
