name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["3.2", "4.0", "4.1", "4.2", "5.0"]
        exclude:
          - python-version: "3.7"
            django-version: "4.0"
          - python-version: "3.7"
            django-version: "4.1"
          - python-version: "3.7"
            django-version: "4.2"
          - python-version: "3.7"
            django-version: "5.0"
          - python-version: "3.8"
            django-version: "5.0"
          - python-version: "3.9"
            django-version: "5.0"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "requirements*.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.in
      - name: Install Django ${{ matrix.django-version }}
        run: |
          pip install Django~=${{ matrix.django-version }}
      - name: Test with pytest
        run: |
          pytest
